CREATE OR REPLACE TABLE LOG.ODBCSQL_AUDIT FOR SYSTEM NAME LOGQZDAINI ( 
	UTILISATEUR FOR COLUMN PROFIL     CHAR(10) CCSID 1147 NOT NULL DEFAULT '' , 
	DATE_CONNEXION FOR COLUMN DTCONNEX   TIMESTAMP GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP NOT NULL , 
	REQUETE_SQL FOR COLUMN REQ_SQL  VARCHAR(512) CCSID 1147 NOT NULL DEFAULT '' , 
	FONCTION FOR COLUMN FONCTION  CHAR(4) CCSID 1147 NOT NULL DEFAULT '' ,
    FONCTION_LIBELLE FOR COLUMN FONC_LIB VARCHAR(30) CCSID 1147 NOT NULL DEFAULT '' )   
	  
	RCDFMT LOGQZDASQL ; 
  
LABEL ON TABLE LOG.ODBCSQL_AUDIT 
	IS 'Fichier de log requêtes SQL' ; 
  
LABEL ON COLUMN LOG.ODBCSQL_AUDIT 
( UTILISATEUR IS 'Profil utilisateur   ' , 
	DATE_CONNEXION IS 'Date de requête       ' , 
	REQUETE_SQL IS 'Requêtes SQL (début)       ' , 
	FONCTION IS 'Fonction utilisée       ',
    FONCTION_LIBELLE IS 'Libellé de la fonction'  ) ; 
  
LABEL ON COLUMN LOG.ODBCSQL_AUDIT 
( UTILISATEUR TEXT IS 'Profil utilisateur' , 
	DATE_CONNEXION TEXT IS 'Date de requête' ) ; 
   
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON LOG.ODBCSQL_AUDIT TO QPGMR WITH GRANT OPTION ; 